In [150]:
import pandas as pd 
import tensorflow
from tensorflow import keras
from keras import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

df = pd.read_csv("../Churn_Modelling.csv")

In [151]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [152]:
df = df.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [153]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [154]:
le = LabelEncoder()
for col in df.select_dtypes("object"):
    df[col] = le.fit_transform(df[col])
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64,0
9996,516,0,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,0,0,36,7,0.00,1,0,1,42085.58,1
9998,772,1,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,0,0,28,4,130142.79,1,1,0,38190.78,0

In [155]:
Y = df["Exited"]
X = df.drop(["Exited"], axis=1)
Xtrain, Xtest,ytrain,ytest = train_test_split(X,Y, test_size=0.2, shuffle=True, random_state=42)

In [156]:
#scaling es muy importante para gardient descent en NN, SVM, distance measurementes, knn 
scaler = MinMaxScaler()
#important to apply it after splitting bc it affects data leakage and overfitting if combined with xtest , por eso debe ser independiente
Xtrain = scaler.fit_transform(Xtrain)
#se aplican los parameters learned from the training set
Xtest = scaler.transform(Xtest)

In [157]:
import tensorflow as tf
from keras.layers import Dense, Dropout, BatchNormalization
from keras.optimizers import Adam
from sklearn.metrics import classification_report,confusion_matrix
import numpy as np


unique_classes = np.unique(ytrain)

In [158]:
from keras.callbacks import EarlyStopping

from keras.regularizers import l2

early_stopping = EarlyStopping(
    monitor='recall',    # Metric to monitor
    patience=10,            # Number of epochs with no improvement after which training will be stopped
    restore_best_weights=True,  # Restore model weights from the epoch with the best value of the monitored quantity
    mode = "max"
    
)

model = Sequential()
model.add(Dense(units=10,  activation="relu"))
model.add(BatchNormalization())
model.add(Dense(units=80,  activation="relu"))
model.add(BatchNormalization())
model.add(Dense(units=600, activation="relu" ))
model.add(BatchNormalization())
model.add(Dropout(0.3))
model.add(Dense(units=400, activation="relu"))
model.add(BatchNormalization())
model.add(Dropout(0.15))
model.add(Dense(units=100, activation="relu"))
model.add(BatchNormalization())
model.add(Dropout(0.15))
model.add(Dense(units=100, activation="relu" ))
model.add(BatchNormalization())
model.add(Dropout(0.05))
model.add(Dense(units=1, activation="sigmoid"))

model.compile(optimizer=Adam(), loss="binary_crossentropy", metrics=["recall"])
model.fit(x=Xtrain, y=ytrain, epochs=100, validation_split=0.2, callbacks=[early_stopping])

Epoch 1/100

200/200 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 0.6626 - recall: 0.3337 - val_loss: 0.4932 - val_recall: 0.0000e+00
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4961 - recall: 0.1089 - val_loss: 0.4645 - val_recall: 0.0559
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4712 - recall: 0.1502 - val_loss: 0.4351 - val_recall: 0.2453
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4384 - recall: 0.2791 - val_loss: 0.4051 - val_recall: 0.3913
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4389 - recall: 0.2669 - val_loss: 0.3889 - val_recall: 0.3820
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4128 - recall: 0.3641 - val_loss: 0.3858 - val_recall: 0.3571
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4014 - recall: 0.3716 - val_loss: 0.3755 - val_recall: 0.3665
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3732 - recall: 0.3925 - val_loss: 0.3621 - val_recall: 0.3665
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3943 - recall: 0.3812 - val_loss: 0.3673 - val_recall: 0.3571
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3637 - recall: 0.4047 - val_loss: 0.3602 - val_recall: 0.4099
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3894 - recall: 0.3804 - val_loss: 0.3697 - val_recall: 0.4565
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3721 - recall: 0.4400 - val_loss: 0.3615 - val_recall: 0.3634
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3525 - recall: 0.4565 - val_loss: 0.3499 - val_recall: 0.3385
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3604 - recall: 0.4371 - val_loss: 0.3659 - val_recall: 0.3571
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3653 - recall: 0.4160 - val_loss: 0.3584 - val_recall: 0.4317
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3600 - recall: 0.4568 - val_loss: 0.3591 - val_recall: 0.3509
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3678 - recall: 0.4048 - val_loss: 0.3550 - val_recall: 0.3758
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3646 - recall: 0.4123 - val_loss: 0.3634 - val_recall: 0.3571
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3590 - recall: 0.4411 - val_loss: 0.3529 - val_recall: 0.3820
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3588 - recall: 0.4484 - val_loss: 0.3522 - val_recall: 0.3944
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3511 - recall: 0.4300 - val_loss: 0.3514 - val_recall: 0.3696
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3521 - recall: 0.4325 - val_loss: 0.3458 - val_recall: 0.3789
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3584 - recall: 0.4092 - val_loss: 0.3522 - val_recall: 0.4193
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3524 - recall: 0.4221 - val_loss: 0.3508 - val_recall: 0.4006
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3587 - recall: 0.4310 - val_loss: 0.3472 - val_recall: 0.4783
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3467 - recall: 0.4615 - val_loss: 0.3458 - val_recall: 0.4596
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3454 - recall: 0.4452 - val_loss: 0.3511 - val_recall: 0.3944
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3454 - recall: 0.4449 - val_loss: 0.3509 - val_recall: 0.4720
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3485 - recall: 0.4231 - val_loss: 0.3524 - val_recall: 0.4534
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3381 - recall: 0.4695 - val_loss: 0.3522 - val_recall: 0.4224
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3442 - recall: 0.4531 - val_loss: 0.3534 - val_recall: 0.4286
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3515 - recall: 0.4743 - val_loss: 0.3515 - val_recall: 0.4193
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3240 - recall: 0.4447 - val_loss: 0.3517 - val_recall: 0.5280
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3398 - recall: 0.4972 - val_loss: 0.3543 - val_recall: 0.4193
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3373 - recall: 0.4715 - val_loss: 0.3598 - val_recall: 0.5000
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3405 - recall: 0.4767 - val_loss: 0.3537 - val_recall: 0.4627
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3375 - recall: 0.4881 - val_loss: 0.3617 - val_recall: 0.4037
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3346 - recall: 0.4463 - val_loss: 0.3569 - val_recall: 0.4193
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3355 - recall: 0.4976 - val_loss: 0.3477 - val_recall: 0.4286
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3404 - recall: 0.4771 - val_loss: 0.3718 - val_recall: 0.3727
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3316 - recall: 0.4761 - val_loss: 0.3650 - val_recall: 0.4534
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3354 - recall: 0.4652 - val_loss: 0.3560 - val_recall: 0.4876
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3436 - recall: 0.4793 - val_loss: 0.3612 - val_recall: 0.4037
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3159 - recall: 0.4939 - val_loss: 0.3555 - val_recall: 0.4783
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3289 - recall: 0.4726 - val_loss: 0.3637 - val_recall: 0.4348
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3300 - recall: 0.5048 - val_loss: 0.3533 - val_recall: 0.4596
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3274 - recall: 0.5020 - val_loss: 0.3562 - val_recall: 0.4720
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3247 - recall: 0.5033 - val_loss: 0.3569 - val_recall: 0.4969
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3327 - recall: 0.5185 - val_loss: 0.3527 - val_recall: 0.5031
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3262 - recall: 0.5006 - val_loss: 0.3674 - val_recall: 0.4565
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3338 - recall: 0.5123 - val_loss: 0.3628 - val_recall: 0.4876
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3247 - recall: 0.5095 - val_loss: 0.3542 - val_recall: 0.4814
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3394 - recall: 0.4792 - val_loss: 0.3611 - val_recall: 0.3975
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3231 - recall: 0.4796 - val_loss: 0.3677 - val_recall: 0.4472
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3274 - recall: 0.4847 - val_loss: 0.3568 - val_recall: 0.4752
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3201 - recall: 0.5127 - val_loss: 0.3690 - val_recall: 0.4534
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3312 - recall: 0.4924 - val_loss: 0.3584 - val_recall: 0.4627
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3127 - recall: 0.5057 - val_loss: 0.3787 - val_recall: 0.4534
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3246 - recall: 0.5237 - val_loss: 0.3753 - val_recall: 0.4472
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3076 - recall: 0.5356 - val_loss: 0.3557 - val_recall: 0.4720
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3213 - recall: 0.5058 - val_loss: 0.3646 - val_recall: 0.5311
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3120 - recall: 0.5193 - val_loss: 0.3651 - val_recall: 0.4627
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3160 - recall: 0.5264 - val_loss: 0.3652 - val_recall: 0.3634
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3083 - recall: 0.5206 - val_loss: 0.3677 - val_recall: 0.4286
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3103 - recall: 0.5428 - val_loss: 0.3709 - val_recall: 0.4658
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3230 - recall: 0.5139 - val_loss: 0.3630 - val_recall: 0.4814
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3132 - recall: 0.5425 - val_loss: 0.3665 - val_recall: 0.4224
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3340 - recall: 0.5041 - val_loss: 0.3662 - val_recall: 0.4658
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3176 - recall: 0.5118 - val_loss: 0.3795 - val_recall: 0.4224
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3107 - recall: 0.5090 - val_loss: 0.3809 - val_recall: 0.4565
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3157 - recall: 0.5178 - val_loss: 0.3809 - val_recall: 0.3913
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3163 - recall: 0.5084 - val_loss: 0.3959 - val_recall: 0.4752
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3093 - recall: 0.4958 - val_loss: 0.3638 - val_recall: 0.4752
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3129 - recall: 0.5438 - val_loss: 0.3689 - val_recall: 0.4193
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3048 - recall: 0.5312 - val_loss: 0.3684 - val_recall: 0.4689
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3172 - recall: 0.5234 - val_loss: 0.3660 - val_recall: 0.4907
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3082 - recall: 0.5394 - val_loss: 0.3783 - val_recall: 0.4689
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3010 - recall: 0.5382 - val_loss: 0.3712 - val_recall: 0.3696
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3023 - recall: 0.5323 - val_loss: 0.3739 - val_recall: 0.4193
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3106 - recall: 0.5457 - val_loss: 0.3785 - val_recall: 0.4006
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3035 - recall: 0.5305 - val_loss: 0.3747 - val_recall: 0.4503
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3121 - recall: 0.5253 - val_loss: 0.3854 - val_recall: 0.4503
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3165 - recall: 0.5340 - val_loss: 0.3743 - val_recall: 0.4255
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3036 - recall: 0.5115 - val_loss: 0.3808 - val_recall: 0.5000
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3076 - recall: 0.5428 - val_loss: 0.3768 - val_recall: 0.4689
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3004 - recall: 0.5789 - val_loss: 0.3696 - val_recall: 0.5000

In [159]:
loss, recall = model.evaluate(Xtest, ytest)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3657 - recall: 0.5109

In [160]:
ypred = (model.predict(Xtest) > 0.5).astype("int32")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [161]:
ypred

array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]])

In [162]:
print(classification_report(ytest, ypred))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1607
           1       0.69      0.51      0.59       393

    accuracy                           0.86      2000
   macro avg       0.79      0.73      0.75      2000
weighted avg       0.85      0.86      0.85      2000

In [163]:
import pickle
with open("neural3.pkl", "wb") as file:
    pickle.dump(model, file)