In [156]:
import pandas as pd 
import tensorflow
from tensorflow import keras
from keras import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

df = pd.read_csv("../Churn_Modelling.csv")

In [157]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [158]:
df = df.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [159]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [160]:
le = LabelEncoder()
for col in df.select_dtypes("object"):
    df[col] = le.fit_transform(df[col])
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64,0
9996,516,0,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,0,0,36,7,0.00,1,0,1,42085.58,1
9998,772,1,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,0,0,28,4,130142.79,1,1,0,38190.78,0

In [161]:
Y = df["Exited"]
X = df.drop(["Exited"], axis=1)
Xtrain, Xtest,ytrain,ytest = train_test_split(X,Y, test_size=0.2, shuffle=True, random_state=42)

In [162]:
#scaling es muy importante para gardient descent en NN, SVM, distance measurementes, knn 
scaler = MinMaxScaler()
#important to apply it after splitting bc it affects data leakage and overfitting if combined with xtest , por eso debe ser independiente
Xtrain = scaler.fit_transform(Xtrain)
#se aplican los parameters learned from the training set
Xtest = scaler.transform(Xtest)

In [163]:
import tensorflow as tf
from keras.layers import Dense, Dropout, BatchNormalization
from keras.optimizers import Adam
from sklearn.metrics import classification_report,confusion_matrix
import numpy as np


unique_classes = np.unique(ytrain)

In [164]:
from keras.callbacks import EarlyStopping


early_stopping = EarlyStopping(
    monitor='recall',    # Metric to monitor
    patience=10,            # Number of epochs with no improvement after which training will be stopped
    restore_best_weights=True,  # Restore model weights from the epoch with the best value of the monitored quantity
    mode = "max"
    
)

model = Sequential()
model.add(Dense(units=400,  activation="relu"))
model.add(BatchNormalization())
model.add(Dropout(0.4))
model.add(Dense(units=600, activation="relu" ))
model.add(BatchNormalization())
model.add(Dropout(0.4))
model.add(Dense(units=300, activation="relu"))
model.add(BatchNormalization())
model.add(Dense(units=100, activation="relu"))
model.add(BatchNormalization())
model.add(Dense(units=100, activation="relu"))
model.add(BatchNormalization())
model.add(Dense(units=1, activation="sigmoid"))

model.compile(optimizer=Adam(), loss="binary_crossentropy", metrics=["recall"])
model.fit(x=Xtrain, y=ytrain, epochs=100, validation_split=0.2, callbacks=[early_stopping])

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 0.6413 - recall: 0.4288 - val_loss: 0.4860 - val_recall: 0.0000e+00
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4167 - recall: 0.3701 - val_loss: 0.4197 - val_recall: 0.2422
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3971 - recall: 0.3988 - val_loss: 0.3663 - val_recall: 0.3758
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4045 - recall: 0.3646 - val_loss: 0.3666 - val_recall: 0.4255
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3757 - recall: 0.3946 - val_loss: 0.3822 - val_recall: 0.5062
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3802 - recall: 0.4283 - val_loss: 0.3637 - val_recall: 0.4317
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3709 - recall: 0.4115 - val_loss: 0.3648 - val_recall: 0.4627
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3560 - recall: 0.4353 - val_loss: 0.3649 - val_recall: 0.3944
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3587 - recall: 0.4400 - val_loss: 0.3525 - val_recall: 0.3882
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3724 - recall: 0.4055 - val_loss: 0.3505 - val_recall: 0.4814
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3632 - recall: 0.4705 - val_loss: 0.3543 - val_recall: 0.3851
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3750 - recall: 0.4219 - val_loss: 0.3559 - val_recall: 0.4534
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3531 - recall: 0.4649 - val_loss: 0.3648 - val_recall: 0.3540
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3634 - recall: 0.4327 - val_loss: 0.3595 - val_recall: 0.3975
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3567 - recall: 0.4270 - val_loss: 0.3608 - val_recall: 0.3261
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3504 - recall: 0.4551 - val_loss: 0.3587 - val_recall: 0.4379
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3414 - recall: 0.4796 - val_loss: 0.3417 - val_recall: 0.4286
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3502 - recall: 0.4539 - val_loss: 0.3467 - val_recall: 0.5093
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3559 - recall: 0.4757 - val_loss: 0.3555 - val_recall: 0.4348
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3526 - recall: 0.4859 - val_loss: 0.3571 - val_recall: 0.4596
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3329 - recall: 0.4737 - val_loss: 0.3515 - val_recall: 0.4503
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3305 - recall: 0.4744 - val_loss: 0.3515 - val_recall: 0.4627
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3488 - recall: 0.4396 - val_loss: 0.3742 - val_recall: 0.5994
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3481 - recall: 0.4922 - val_loss: 0.3556 - val_recall: 0.3913
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3410 - recall: 0.4920 - val_loss: 0.3489 - val_recall: 0.4317
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3400 - recall: 0.4809 - val_loss: 0.3630 - val_recall: 0.3509
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3354 - recall: 0.4521 - val_loss: 0.3573 - val_recall: 0.5217
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3314 - recall: 0.4671 - val_loss: 0.3529 - val_recall: 0.4410
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3455 - recall: 0.4552 - val_loss: 0.3506 - val_recall: 0.4596
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3410 - recall: 0.4542 - val_loss: 0.3653 - val_recall: 0.4472
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3382 - recall: 0.4510 - val_loss: 0.3687 - val_recall: 0.4689
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3375 - recall: 0.5090 - val_loss: 0.3533 - val_recall: 0.4783
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3338 - recall: 0.4773 - val_loss: 0.3528 - val_recall: 0.4099
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3405 - recall: 0.4593 - val_loss: 0.3468 - val_recall: 0.5124
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3349 - recall: 0.5081 - val_loss: 0.3568 - val_recall: 0.4379
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3325 - recall: 0.4696 - val_loss: 0.3498 - val_recall: 0.4565
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3310 - recall: 0.4852 - val_loss: 0.3497 - val_recall: 0.4379
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3321 - recall: 0.4521 - val_loss: 0.3620 - val_recall: 0.5155
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3469 - recall: 0.4622 - val_loss: 0.3503 - val_recall: 0.4907
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3370 - recall: 0.4901 - val_loss: 0.3527 - val_recall: 0.4969
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3361 - recall: 0.4701 - val_loss: 0.3505 - val_recall: 0.4099
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3339 - recall: 0.4771 - val_loss: 0.3613 - val_recall: 0.4379
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3219 - recall: 0.4961 - val_loss: 0.3639 - val_recall: 0.4596
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3291 - recall: 0.4843 - val_loss: 0.3646 - val_recall: 0.4658
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3298 - recall: 0.5216 - val_loss: 0.3658 - val_recall: 0.4099
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3188 - recall: 0.5032 - val_loss: 0.3585 - val_recall: 0.4503
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3072 - recall: 0.5185 - val_loss: 0.3714 - val_recall: 0.4006
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3124 - recall: 0.5387 - val_loss: 0.3661 - val_recall: 0.5000
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3159 - recall: 0.5330 - val_loss: 0.3636 - val_recall: 0.4286
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3218 - recall: 0.5110 - val_loss: 0.3718 - val_recall: 0.3851
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3110 - recall: 0.5230 - val_loss: 0.3671 - val_recall: 0.4907
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3118 - recall: 0.5384 - val_loss: 0.3723 - val_recall: 0.4255
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3179 - recall: 0.5227 - val_loss: 0.3652 - val_recall: 0.4658
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3128 - recall: 0.5119 - val_loss: 0.3602 - val_recall: 0.4658
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3211 - recall: 0.5162 - val_loss: 0.3634 - val_recall: 0.4752
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3160 - recall: 0.5341 - val_loss: 0.3615 - val_recall: 0.4783
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3150 - recall: 0.5388 - val_loss: 0.3617 - val_recall: 0.4689
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3210 - recall: 0.5282 - val_loss: 0.3646 - val_recall: 0.4783
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3030 - recall: 0.5265 - val_loss: 0.3691 - val_recall: 0.4938
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3128 - recall: 0.5499 - val_loss: 0.3619 - val_recall: 0.4472
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3188 - recall: 0.5453 - val_loss: 0.3657 - val_recall: 0.4441
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2995 - recall: 0.5264 - val_loss: 0.3692 - val_recall: 0.4814
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3152 - recall: 0.5014 - val_loss: 0.3688 - val_recall: 0.4317
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3064 - recall: 0.5309 - val_loss: 0.3685 - val_recall: 0.5000
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3178 - recall: 0.5472 - val_loss: 0.3676 - val_recall: 0.4627
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3075 - recall: 0.5492 - val_loss: 0.3628 - val_recall: 0.4472
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3001 - recall: 0.5657 - val_loss: 0.3751 - val_recall: 0.4410
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3063 - recall: 0.5488 - val_loss: 0.3735 - val_recall: 0.4379
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3024 - recall: 0.5480 - val_loss: 0.3704 - val_recall: 0.5155
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2970 - recall: 0.5551 - val_loss: 0.3637 - val_recall: 0.4317
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3001 - recall: 0.5679 - val_loss: 0.3772 - val_recall: 0.4503
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3126 - recall: 0.5187 - val_loss: 0.3700 - val_recall: 0.5093
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3122 - recall: 0.5513 - val_loss: 0.3666 - val_recall: 0.4410
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3003 - recall: 0.5494 - val_loss: 0.3718 - val_recall: 0.4006
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2914 - recall: 0.5529 - val_loss: 0.3648 - val_recall: 0.4534
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2938 - recall: 0.5618 - val_loss: 0.3824 - val_recall: 0.3913
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.3055 - recall: 0.5051 - val_loss: 0.3804 - val_recall: 0.5031
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.2882 - recall: 0.5837 - val_loss: 0.3754 - val_recall: 0.4720
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.2901 - recall: 0.5581 - val_loss: 0.3919 - val_recall: 0.4472
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2939 - recall: 0.5700 - val_loss: 0.3791 - val_recall: 0.4472
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3034 - recall: 0.5375 - val_loss: 0.3753 - val_recall: 0.5248
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2878 - recall: 0.5533 - val_loss: 0.3822 - val_recall: 0.4503
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2858 - recall: 0.5924 - val_loss: 0.3892 - val_recall: 0.4689
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2939 - recall: 0.5460 - val_loss: 0.3737 - val_recall: 0.4720
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2988 - recall: 0.5756 - val_loss: 0.3873 - val_recall: 0.3820
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2865 - recall: 0.5698 - val_loss: 0.4022 - val_recall: 0.3540
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2905 - recall: 0.5137 - val_loss: 0.3816 - val_recall: 0.4969
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2858 - recall: 0.5638 - val_loss: 0.3823 - val_recall: 0.5093
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2883 - recall: 0.5891 - val_loss: 0.3822 - val_recall: 0.4534
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2930 - recall: 0.5509 - val_loss: 0.3875 - val_recall: 0.4317
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2902 - recall: 0.5292 - val_loss: 0.3871 - val_recall: 0.4534
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2848 - recall: 0.5616 - val_loss: 0.3838 - val_recall: 0.5000
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.2804 - recall: 0.5972 - val_loss: 0.3805 - val_recall: 0.4658

In [165]:
loss, recall = model.evaluate(Xtest, ytest)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3604 - recall: 0.5464

In [166]:
ypred = (model.predict(Xtest) > 0.5).astype("int32")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [167]:
ypred

array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]])

In [168]:
print(classification_report(ytest, ypred))

              precision    recall  f1-score   support

           0       0.89      0.94      0.91      1607
           1       0.68      0.51      0.59       393

    accuracy                           0.86      2000
   macro avg       0.79      0.73      0.75      2000
weighted avg       0.85      0.86      0.85      2000

In [169]:
import pickle
with open("neural3.pkl", "wb") as file:
    pickle.dump(model, file)